package com.qlhx.service.wechat.realize.dao;

import com.qlhx.service.wechat.realize.model.BlackListBo;
import com.qlhx.service.wechat.realize.model.Blacklist;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface BlacklistMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_blacklist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_blacklist
     *
     * @mbggenerated
     */
    int insert(Blacklist record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_blacklist
     *
     * @mbggenerated
     */
    int insertSelective(Blacklist record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_blacklist
     *
     * @mbggenerated
     */
    Blacklist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_blacklist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Blacklist record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_blacklist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Blacklist record);

    List<BlackListBo> selectBlacklistBo(Map<String, Object> modelMap);

    Integer selectBlacklistByVid(String vId);

    Integer selectBlackByIdNum(@Param("idNum") String idNum);
    
    Integer selectBlackByTel(String tel);

    /**
     * 
     * <p>
     * Title:根据访客id查询黑名单信息
     * </p>
     * <p>
     * Description:
     * </p>
     *
     * @param vID
     * @return
     * @throws Exception
     */
    Blacklist findBlackListByVisitorId(@Param("vID") Integer vID)
	    throws Exception;
    
    Blacklist selectBlacklistByPama(Blacklist blacklist) throws Exception;
    
    int updateByCompanyCodeAndId(Blacklist blacklist) throws Exception;
    
    BlackListBo selectBlackVisitorByPrimaryKey(Integer id);
    
    int selectBlacklistBoCount(Map param);
    
    BlackListBo selectBlackVisitorByParam(Map param);
    
    int deleteBlackByVid(Map param);

}