package com.qlhx.service.wechat.realize.dao;

import com.qlhx.service.wechat.realize.model.ComboResult;
import com.qlhx.service.wechat.realize.model.Department;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * Created by rongcan on 2017/7/4.
 */
public interface DepartmentMapper {

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_res
     *
     * @mbggenerated
     */
    int insertSelective(Department department) throws Exception;

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_res
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Department department);

    List<ComboResult> selectDepartmentComboResult();

    List<Department> findAllDept();

    Department selectDeptByName(@Param("dname") String trim);

    /**
     * 根据同步部门id获取指定部门信息
     * 
     * @param syncId
     * @return
     * @throws Exception
     */
    Department selectDepBySyncId(@Param("syncId") Integer syncId,
                                 @Param("companyNum") String companyNum) throws Exception;

    /**
     * 根据企业编号查询部门信息列表
     * 
     * @param companyNum
     * @return
     * @throws Exception
     */
    List<Department> findDepByCompanyNum(@Param("companyNum") String companyNum)
	    throws Exception;
    
    int updateByCompanyCodeAndId(Department department) throws Exception;
}
