package com.qlhx.service.wechat.realize.dao;


import com.qlhx.service.wechat.realize.model.DraginRes;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DraginResMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_dragin_res
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_dragin_res
     *
     * @mbggenerated
     */
    int insert(DraginRes record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_dragin_res
     *
     * @mbggenerated
     */
    int insertSelective(DraginRes record) throws Exception;

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_dragin_res
     *
     * @mbggenerated
     */
    DraginRes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_dragin_res
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DraginRes record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_dragin_res
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DraginRes record);

    /**
     * 
     * <p>
     * Title:根据访客记录ID删除该记录访客携带物品
     * </p>
     * <p>
     * Description:
     * </p>
     *
     * @param arId
     * @return
     * @throws Exception
     */
    Integer deleteByArId(@Param("arId") Integer arId) throws Exception;

    /**
     * 
     * <p>
     * Title:获取访客某次来访带入物品列表
     * </p>
     * <p>
     * Description:
     * </p>
     *
     * @return
     * @throws Exception
     */
    List<DraginRes> findDraginResByarId(@Param("arID") Integer arID)
	    throws Exception;

}