package com.qlhx.service.wechat.realize.dao;

import com.qlhx.service.wechat.realize.model.EntranceGuard;
import com.qlhx.service.wechat.realize.model.EntranceGuardBo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EntranceGuardMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_entrance_guard
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_entrance_guard
     *
     * @mbggenerated
     */
    int insert(EntranceGuard record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_entrance_guard
     *
     * @mbggenerated
     */
    int insertSelective(EntranceGuard record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_entrance_guard
     *
     * @mbggenerated
     */
    EntranceGuard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_entrance_guard
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EntranceGuard record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_entrance_guard
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EntranceGuard record);

    /**
     * <p>
     * Title:根据门禁编码和员工id（被访人）查询通道权限
     * </p>
     * <p>
     * Description:
     * </p>
     *
     * @param egNum
     * @param uId
     * @return
     * @throws Exception
     */
    EntranceGuard findOpenDoorPermission(@Param("egNum") String egNum,
                                         @Param("uId") Long uId) throws Exception;

    EntranceGuard selectEntranceByEnnum(String egNum);

    List<EntranceGuardBo> selectAccessById(@Param("uid") Integer id);

    List<EntranceGuard> findAllUseEntranceGuard() throws Exception;
}