package com.qlhx.service.wechat.realize.dao;

import com.qlhx.service.wechat.realize.model.FaceModels;
import com.qlhx.service.wechat.realize.model.VVisitor;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FaceModelsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_facemodels
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_facemodels
     *
     * @mbggenerated
     */
    int insert(FaceModels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_facemodels
     *
     * @mbggenerated
     */
    int insertSelective(FaceModels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_facemodels
     *
     * @mbggenerated
     */
    FaceModels selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_facemodels
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FaceModels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_facemodels
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FaceModels record);

    /**
     * 根据用户ID获取绑定的模型列表
     * @param uid
     * @return
     */
    List<FaceModels> selectByUid(String uid);

    /***
     * 是否存在绑定的id
     * @param faceModels
     * @return
     */
    int existUserFaceModel(FaceModels faceModels);

    /**
     * 根据人脸ID查询访客信息
     * @param faceids
     * @return
     */
    VVisitor findVisitorByFaceid(@Param("faceids") String faceids);

    /**
     * 删除人脸绑定通人员id
     * @param faceModels
     */
    void deletebindfacebyuid(FaceModels faceModels);

    /**
     * 通过faceids查找绑定的人员id
     * @param faceModels
     * @return
     */
    FaceModels GetFaceModelByfaceids(FaceModels faceModels);

}