package com.qlhx.service.wechat.realize.dao;


import com.qlhx.service.wechat.realize.model.FingerPrint;
import com.qlhx.service.wechat.realize.model.VVisitor;

import java.util.List;

public interface FingerPrintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_fingerprints
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_fingerprints
     *
     * @mbggenerated
     */
    int insert(FingerPrint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_fingerprints
     *
     * @mbggenerated
     */
    int insertSelective(FingerPrint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_fingerprints
     *
     * @mbggenerated
     */
    FingerPrint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_fingerprints
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FingerPrint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_fingerprints
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FingerPrint record);


    /**
     * 根据用户ID获取绑定的模型列表
     * @param uid
     * @return
     */
    List<FingerPrint> selectByUid(String uid);

    /***
     * 是否存在绑定的id
     * @param fingerPrint
     * @return
     */
    int existFingerPrint(FingerPrint fingerPrint);

    /**
     * 根据人脸ID查询访客信息
     * @param fingerPrint
     * @return
     */
    VVisitor findVisitorByfingerids(FingerPrint fingerPrint);

    /**
     * 删除绑定指纹
     * @param fingerPrint
     */
    void deletebindfingerbyuid(FingerPrint fingerPrint);

    /**
     * 通过fingerids查找绑定的人员id
     * @param fingerPrint
     * @return
     */
    FingerPrint GetFingerPrintByfingerids(FingerPrint fingerPrint);
}