package com.qlhx.service.wechat.realize.dao;


import com.qlhx.service.wechat.realize.model.SwingCardRecord;

public interface SwingCardRecordMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_swing_card_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_swing_card_record
     *
     * @mbggenerated
     */
    int insert(SwingCardRecord record);

    /**
     * 
     * <p>
     * Title:添加信息的员工、访客刷卡记录
     * </p>
     * <p>
     * Description:
     * </p>
     *
     * @param record
     * @return
     * @throws Exception
     */
    int insertSelective(SwingCardRecord record) throws Exception;

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_swing_card_record
     *
     * @mbggenerated
     */
    SwingCardRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_swing_card_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SwingCardRecord record) throws Exception;

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_swing_card_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SwingCardRecord record);
    
    SwingCardRecord selectSwingCardRecordByPama(SwingCardRecord record) throws Exception;

}