package com.qlhx.service.wechat.realize.dao;


import com.qlhx.service.wechat.realize.model.Thoroughfare;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ThoroughfareMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_thoroughfare
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_thoroughfare
     *
     * @mbggenerated
     */
    int insert(Thoroughfare record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_thoroughfare
     *
     * @mbggenerated
     */
    int insertSelective(Thoroughfare record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_thoroughfare
     *
     * @mbggenerated
     */
    Thoroughfare selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_thoroughfare
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Thoroughfare record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_thoroughfare
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Thoroughfare record);

    void deleteByUid(@Param("uid") Integer uid);

    void deleteByDeptid(@Param("deptid") Integer deptid);

    List<Thoroughfare> selectByUserId(@Param("uId") Integer userId);
}