package com.qlhx.service.wechat.realize.dao;


import com.qlhx.service.wechat.realize.model.ComboResult;
import com.qlhx.service.wechat.realize.model.UUserNation;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UUserNationMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_natiom
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer nationnum);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_natiom
     *
     * @mbggenerated
     */
    int insert(UUserNation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_natiom
     *
     * @mbggenerated
     */
    int insertSelective(UUserNation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_natiom
     *
     * @mbggenerated
     */
    UUserNation selectByPrimaryKey(Integer nationnum);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_natiom
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UUserNation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_natiom
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UUserNation record);

    List<ComboResult> selectNationComboResult();

    UUserNation selectByValue(@Param("value") String nName);

    List<UUserNation> selectAllNation();
}