package com.qlhx.service.wechat.realize.dao;


import com.qlhx.service.wechat.realize.model.UUserDep;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UUserDepMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_department
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_department
     *
     * @mbggenerated
     */
    int insert(UUserDep record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_department
     *
     * @mbggenerated
     */
    int insertSelective(UUserDep record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_department
     *
     * @mbggenerated
     */
    UUserDep selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_department
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UUserDep record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_department
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UUserDep record);

    /**
     * 
     * <p>
     * Title:查询所有部门信息列表
     * </p>
     * <p>
     * Description:
     * </p>
     *
     * @return
     * @throws Exception
     */
    List<UUserDep> findDepartment(@Param("companyNum") String companyNum)
	    throws Exception;

    /**
     * 
     * <p>
     * Title:根据员工id获取员工部门
     * </p>
     * <p>
     * Description:
     * </p>
     *
     * @param uID
     * @return
     * @throws Exception
     */
    UUserDep findDepartmentByUid(@Param("uID") Integer uID) throws Exception;
}