package com.qlhx.service.wechat.realize.dao;



import com.qlhx.service.wechat.realize.model.ComboResult;
import com.qlhx.service.wechat.realize.model.VisitReasons;

import java.util.List;

public interface VisitReasonsMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_visit_reasons
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_visit_reasons
     *
     * @mbggenerated
     */
    int insert(VisitReasons record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_visit_reasons
     *
     * @mbggenerated
     */
    int insertSelective(VisitReasons record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_visit_reasons
     *
     * @mbggenerated
     */
    VisitReasons selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_visit_reasons
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VisitReasons record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table u_visit_reasons
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VisitReasons record);

    /**
     * 
     * <p>
     * Title:获取来访事由列表信息
     * </p>
     * <p>
     * Description:
     * </p>
     *
     * @return
     * @throws Exception
     */
    List<VisitReasons> findReasons() throws Exception;

    List<ComboResult> GetVisitorReasonComboResult();
}