server:
  port: 12003

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #当前是单节点，不用在其他注册中兴抓取数据
    service-url:
      #单机
      defaultZone: http://qlhx:qlhx123456@${eureka.instance.hostname}:${server.port}/eureka/
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      #      defaultZone: http://eureka2.com:12002/eureka/,http://eureka3.com:12003/eureka/
 

#安全认证
spring:
  security:
    user:
      name: qlhx
      password: qlhx123456