eureka:
 instance:
   instance-id: service-gateway
   appname: ${spring.application.name}
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/

server:
  port: 8888


#服务名
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes: 
      #基础微服务
      - id: base
        uri: lb://service-base
        predicates:
          - Path=/base/**
        filters:
          - StripPrefix=1
      #控制微服务   
      - id: control
        uri: lb://service-control
        predicates:
          - Path=/control/**
        filters:
          - StripPrefix=1
      #门禁微服务
      - id: door
        uri: lb://service-door
        predicates:
          - Path=/door/**
        filters:
          - StripPrefix=1
      #人脸微服务    
      - id: facedevice
        uri: lb://service-facedevice
        predicates:
          - Path=/facedevice/**
        filters:
          - StripPrefix=1
      #日志微服务  
      - id: logger
        uri: lb://service-logger
        predicates:
          - Path=/logger/**
        filters:
          - StripPrefix=1
      # 权限微服务
      - id: logger
        uri: lb://service-admin
        predicates:
          - Path=/admin/**
        filters:
          - StripPrefix=1




